Linux:
	g++ -o EMOO-Boy main.c DMG.c CPU.c MMU.c Timer.c PPU.c -I /usr/include/SDL2/ -lSDL2  -lGL

Windows:
	g++ -g -I src/include -L src/lib -o EMOO-Boy main.c DMG.c CPU.c MMU.c Timer.c PPU.c -lmingw32 -lSDL2main -lSDL2